
DROP TABLE CAT_CLIENTES;

CREATE TABLE CAT_CLIENTES(
	CAT_CLI_OID INT PRIMARY KEY NOT NULL,
	CAT_CLI_NAME NVARCHAR(30),
	CAT_CLI_AGE DATE NOT NULL,
	CAT_CLI_ADDRESS NVARCHAR(60),
	CAT_CLI_SALARY MONEY DEFAULT 0
);

CREATE TABLE HIST_ORDER(
	HIST_ORD_UID INT PRIMARY KEY NOT NULL,
	HIST_ORD_DATE DATE NOT NULL,
	HIST_ORD_CUSID INT NOT NULL,
	HIST_ORD_AMOUNT MONEY NOT NULL,
	FOREIGN KEY(HIST_ORD_CUSID)REFERENCES CAT_CLIENTES(CAT_CLI_OID) ON DELETE CASCADE
)



SELECT  HIST_ORD_UID, 
		HIST_ORD_DATE, 
		HIST_ORD_AMOUNT, 
		CAT_CLI_NAME 
FROM HIST_ORDER HO 
FULL JOIN CAT_CLIENTES CC 
ON HO.HIST_ORD_CUSID = CC.CAT_CLI_OID;


INSERT INTO CAT_CLIENTES([CAT_CLI_OID]
      ,[CAT_CLI_NAME]
      ,[CAT_CLI_AGE]
      ,[CAT_CLI_ADDRESS]
      ,[CAT_CLI_SALARY])VALUES(1,'Noel', SYSDATETIME(),'Ecatepec',20);