-- Crear secuencias
-- Desde tablas al ser creadas
CREATE TABLE CAT_PERMISOS(
	CAT_PER_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CAT_PER_DESC NVARCHAR(25) NOT NULL
);
-- Desde tabla ya creada antes
CREATE SEQUENCE dbo.SECUENCIA_CLIENTES
	AS INT
		START WITH 1
		INCREMENT BY 1
		MINVALUE 1 MAXVALUE 100
		CYCLE;
	-- Modificar secuencia
ALTER SEQUENCE dbo.SECUENCIA_CLIENTES
		RESTART WITH 22
		INCREMENT BY 1
		MINVALUE 22 MAXVALUE 122
		CYCLE;


--ELABORAR UN PROCEDIMIENTO QUE ME INGRESE 5 REGISTROS 
--OBJETIVO:  CREAR UNA TABLA DE LA SIGUIENT FORMA
-- TBL_REPORTES
-- ID_REPORTE, DESC_REPORTE, CONSECUTIVO_REPORTE, FECHA, PERIODO
-- LOS DATOS PUEDEN SER DEL GUSTO DEL CLIENTE
-- CREAR UN CONSECUTIVO A NIVEL DE TABLA
-- CREAR UN CONSECUVIO NO ASOCIADO A LA TABLE
-- DEBEMOS DE GARANTIZAR QUE SI ALGUN REGISTRO NO SE LLEVA ACABO, SE DEBERA DE DESHACER TODAS LAS TRANSACCIONES
--BEGIN.... ROLLBACK

CREATE TABLE TBL_REPORTES(
	ID_REPORTE INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	DESC_REPORTE NVARCHAR(50),
	CONSECUTIVO_REPORTE INT,
	FECHA DATE,
	PERIODO INT
);

CREATE OR ALTER PROCEDURE @DESC NVARCHAR(50), @PERIODO INT
AS
BEGIN TRANSACTION
	IF()
END;