CREATE PROCEDURE "SP_AREAS"
    @AREADESC VARCHAR(20)
AS
BEGIN
    INSERT INTO AREA VALUES(@AREADESC);
    COMMIT;
END;

-- DROP PROCEDURE "SP_AREAS"
begin
DECLARE @AREADESC VARCHAR(20);
BEGIN TRANSACTION
    SELECT @AREADESC= 'Sistemas';
    INSERT INTO AREA VALUES(@AREADESC);
    COMMIT;
end;

CREATE PROCEDURE "SP_LOGINS"
    @USER VARCHAR(50),
    @PASS VARCHAR(64)
AS
BEGIN
    BEGIN TRY
        --INSERT INTO AREA VALUES(1,'HOLA');
        RAISERROR('Fatal Error',1,1);
    END TRY
    BEGIN CATCH
        
    END CATCH
END;

ROLLBACK;
EXEC SP_AREAS 'Almacén'


SELECT * FROM AREA
DECLARE @ID BIGINT;
DECLARE @DESC VARCHAR(200);
WITH SEARCH AS(
    SELECT A.ID, A.Descripcion FROM AREA A
)select * from SEARCH;