CREATE OR ALTER TRIGGER AUDICRE_USERS
ON USUARIOS
FOR INSERT
AS
BEGIN
	DECLARE @IDU INT;
	DECLARE @NOMBRE NVARCHAR(50);
	DECLARE @EDAD INT;
	DECLARE @USUARIO NVARCHAR(15);
	DECLARE @PASS NVARCHAR(10);
	DECLARE @CREADOR NVARCHAR(100);
	DECLARE @FECHA DATETIME;
	
	SET @IDU = (SELECT  FROM inserted);
	SET @NOMBRE = '';
	SET @EDAD = 0;
	SET @USUARIO = '';
	SET @PASS = '';
	SET @CREADOR = '';
	SET @FECHA = SYSDATETIME();
END;