

-- CONSULTAS

UPDATE HIST_DETALLE SET HIST_OBD_SALIDA = HIST_OBD_ENTRADA + 1;
USE PRACTICAS;
BEGIN
	WITH DETALLE AS(
		SELECT HIST_OBD_MATRICULA MATRICULA, HIST_OBD_EVENTO EVENTO,(DATEDIFF(DAY,HIST_OBD_ENTRADA,HIST_OBD_SALIDA)*24) HORAS FROM HIST_DETALLE
	)
	SELECT D.MATRICULA, 
	D.EVENTO, 
	IIF((SELECT CE.CAT_EVE_MAXTYPE FROM CAT_EVENTOS CE WHERE CE.CAT_EVE_ID = D.EVENTO) < SUM(D.HORAS), (SELECT CE.CAT_EVE_MAXTYPE FROM CAT_EVENTOS CE WHERE CE.CAT_EVE_ID = D.EVENTO), SUM(D.HORAS))
	"TOTAL HORAS" FROM DETALLE D
	GROUP BY D.MATRICULA, D.EVENTO, D.HORAS;
END

-- MATRICULAS

SELECT 

CREATE OR ALTER PROCEDURE SP_MATRICULA @TURNO INT, @MATRICULA NVARCHAR(15) OUTPUT
AS
BEGIN
	SELECT @MATRICULA = CONCAT((SELECT HGD.HIST_GED_GENERACION FROM HIST_GENERACION_DETALLE HGD INNER JOIN
HIST_SEMESTRES HS ON HS.HIST_SEM_ID = HGD.HIST_GED_SEMESTRE AND HS.HIST_SEM_STATUS = 1),
SUBSTRING(CAST(YEAR(GETDATE()) AS NVARCHAR),3,LEN(CAST(YEAR(GETDATE()) AS NVARCHAR))),'20',CAST(@TURNO AS NVARCHAR),REPLACE(STR(CAST(NEXT VALUE FOR dbo.ALUMNOSECUENCIA AS NVARCHAR), 4),' ','0'));	
END

BEGIN
DECLARE @MATRICULA NVARCHAR(15);
EXEC SP_MATRICULA 1, @MATRICULA OUTPUT;
PRINT @MATRICULA;
END



SELECT CA.CAT_ALU_TUTOR TUTOR,COUNT(CA.CAT_ALU_MATRICULA) ALUMNOS FROM CAT_ALUMNOS CA
WHERE CA.CAT_ALU_STATUS <> 4 AND (SELECT COUNT(*) FROM HIST_SEMESTRES HS WHERE HS.HIST_SEM_STATUS = 1 AND GETDATE() 
BETWEEN HS.HIST_SEM_APERTURA AND HS.HIST_SEM_CIERRE) >= 1
GROUP BY CA.CAT_ALU_TUTOR;