--- ALBERTO
USE [s_ALBERTO]
GO
CREATE USER [ALBERTO] FOR LOGIN [ALBERTO] WITH DEFAULT_SCHEMA=[dbo]
GO
use [s_ALBERTO]
GO
GRANT CONNECT TO [ALBERTO]
GO
use [s_ALBERTO]
GO
GRANT CREATE TABLE TO [ALBERTO]
GO
use [s_ALBERTO]
GO
GRANT SELECT TO [ALBERTO]
GO
use [s_ALBERTO]
GO
GRANT UPDATE TO [ALBERTO]
GO
--- ANA
USE [s_ANA]
GO
CREATE USER [ANA] FOR LOGIN [ANA] WITH DEFAULT_SCHEMA=[dbo]
GO
USE [s_ANA]
GO
GRANT CONNECT TO [ANA]
GO
USE [s_ANA]
GO
GRANT CREATE TABLE TO [ANA]
GO
USE [s_ANA]
GO
GRANT SELECT TO [ANA]
GO
USE [s_ANA]
GO
GRANT UPDATE TO [ANA]
GO
--- ANDRES
USE [s_ANDRES]
GO
CREATE USER [ANDRES] FOR LOGIN [ANDRES] WITH DEFAULT_SCHEMA=[dbo]
GO
USE [s_ANDRES]
GO
GRANT CONNECT TO [ANDRES]
GO
USE [s_ANDRES]
GO
GRANT CREATE TABLE TO [ANDRES]
GO
USE [s_ANDRES]
GO
GRANT SELECT TO [ANDRES]
GO
USE [s_ANDRES]
GO
GRANT UPDATE TO [ANDRES]
GO