--- LOGIN ANA
USE [master]
GO
CREATE LOGIN [ANA] WITH PASSWORD=N'a1b2c3d4e5!' MUST_CHANGE, DEFAULT_DATABASE=[PRUEBA], 
CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
USE [PRUEBA]
GO
CREATE USER [ANA] FOR LOGIN [ANA]
GO
-- LOGIN ALBERTO
USE [master]
GO
CREATE LOGIN [ALBERTO] WITH PASSWORD=N'd4e3f2g1h0!' MUST_CHANGE, DEFAULT_DATABASE=[PRUEBA], 
CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
USE [PRUEBA]
GO
CREATE USER [ALBERTO] FOR LOGIN [ALBERTO]
GO
-- LOGIN ANDRES
USE [master]
GO
CREATE LOGIN [ANDRES] WITH PASSWORD=N'f102gh285!' MUST_CHANGE, DEFAULT_DATABASE=[PRUEBA], 
CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
USE [PRUEBA]
GO
CREATE USER [ANDRES] FOR LOGIN [ANDRES]
GO
--- BASES DE DATOS CON LOS NOMBRES
CREATE DATABASE [s_ANA];
CREATE DATABASE [s_ALBERTO];
CREATE DATABASE [s_ANDRES];
