USE [EXAMEN]
CREATE LOGIN ADMINISTRADOR WITH PASSWORD='PASSWORD'
CREATE USER ADMINISTRADOR FOR LOGIN ADMINISTRADOR WITH
DEFAULT_SCHEMA= ESQUEMA_ADMINISTRADOR

CREATE LOGIN CONSULTOR WITH PASSWORD='PASSWORD'
CREATE USER CONSULTOR FOR LOGIN CONSULTOR WITH
DEFAULT_SCHEMA= ESQUEMA_CONSULTOR

CREATE LOGIN ANALISTA WITH PASSWORD='PASSWORD'
CREATE USER ANALISTA FOR LOGIN ANALISTA WITH
DEFAULT_SCHEMA= ESQUEMA_ANALISTA 

GRANT INSERT ON SCHEMA :: [dbo] to ADMINISTRADOR
GRANT SELECT ON SCHEMA :: [dbo] to ADMINISTRADOR
GRANT UPDATE ON SCHEMA :: [dbo] to ADMINISTRADOR
GRANT DELETE ON SCHEMA :: [dbo] to ADMINISTRADOR

GRANT SELECT ON SCHEMA :: [dbo] to CONSULTOR

GRANT INSERT ON SCHEMA :: [dbo] to ANALISTA
GRANT UPDATE ON SCHEMA :: [dbo] to ANALISTA
GRANT DELETE ON SCHEMA :: [dbo] to ANALISTA

