CREATE DATABASE [EXAMEN];
USE [EXAMEN]
GO
-- Tablas
CREATE TABLE CAT_USUARIOS_TYPE(
	CAT_UST_ID INT PRIMARY KEY,
	CAT_UST_DESC NVARCHAR(20)
);
CREATE TABLE CAT_USUARIOS(
	CAT_USU_ID INT PRIMARY KEY,
	CAT_USU_NOMBRE NVARCHAR(20) NOT NULL,
	CAT_USU_PASS NVARCHAR(10) NOT NULL,
	CAT_USU_TYPE INT NOT NULL DEFAULT 2,
	CONSTRAINT FK_USUARIOS_TYPE FOREIGN KEY (CAT_USU_TYPE) REFERENCES CAT_USUARIOS_TYPE(CAT_UST_ID)
);
CREATE TABLE HIST_REGISTROS_BITACORA(
	HIST_REG_ID INT PRIMARY KEY,
	HIST_USUARIO_ID INT DEFAULT 1,
	HIST_REG_PERMISOS NVARCHAR(MAX),
	HIST_REG_BASE NVARCHAR(500) DEFAULT 'EXAMEN',
	HIST_REG_INIT DATETIME DEFAULT GETDATE(),
	HIST_REG_END DATETIME,
	CONSTRAINT FK_USUARIOS FOREIGN KEY (HIST_USUARIO_ID) REFERENCES CAT_USUARIOS(CAT_USU_ID)
);
ALTER TABLE HIST_REGISTROS_BITACORA ADD HIST_REG_FOLIO INTEGER DEFAULT 1;
CREATE SEQUENCE dbo.SECBITAC
	AS INT
		START WITH 1
		INCREMENT BY 1
		MINVALUE 1 MAXVALUE 999
		CYCLE;

-- Usuario y logins
USE [EXAMEN]
CREATE LOGIN ADMINISTRADOR WITH PASSWORD='PASSWORD'
CREATE USER ADMINISTRADOR FOR LOGIN ADMINISTRADOR WITH
DEFAULT_SCHEMA= dbo

CREATE LOGIN CONSULTOR WITH PASSWORD='PASSWORD'
CREATE USER CONSULTOR FOR LOGIN CONSULTOR WITH
DEFAULT_SCHEMA= dbo

CREATE LOGIN ANALISTA WITH PASSWORD='PASSWORD'
CREATE USER ANALISTA FOR LOGIN ANALISTA WITH
DEFAULT_SCHEMA= dbo 
-- Permisos
GRANT INSERT ON SCHEMA :: [dbo] to ADMINISTRADOR
GRANT SELECT ON SCHEMA :: [dbo] to ADMINISTRADOR
GRANT UPDATE ON SCHEMA :: [dbo] to ADMINISTRADOR
GRANT DELETE ON SCHEMA :: [dbo] to ADMINISTRADOR

GRANT SELECT ON SCHEMA :: [dbo] to CONSULTOR
GRANT INSERT ON SCHEMA :: [dbo] to CONSULTOR

GRANT INSERT ON SCHEMA :: [dbo] to ANALISTA
GRANT UPDATE ON SCHEMA :: [dbo] to ANALISTA
GRANT DELETE ON SCHEMA :: [dbo] to ANALISTA
REVOKE DELETE ON SCHEMA:: [dbo] to ANALISTA


USE [EXAMEN]
GRANT SELECT ON SCHEMA :: [dbo] to ANALISTA
EXECUTE AS USER = 'ANALISTA'
SELECT * FROM HIST_REGISTROS_BITACORA;