ALTER DATABASE [UPIITA_BASE] MODIFY FILE (NAME = UPIITA_BASE, FILENAME = 'E:\SQLData\UPIITA_BASE.mdf');
GO
ALTER DATABASE tempdb MODIFY FILE (NAME = UPIITA_BASELOG, FILENAME = 'E:\SQLData\UPIITA_BASELOG.ldf');
GO

USE [UPIITA_BASE];
REVOKE 