USE [master]
GO
CREATE LOGIN [Fernando] WITH PASSWORD=N'123456' MUST_CHANGE, DEFAULT_DATABASE=[UPIITA_BASE], DEFAULT_LANGUAGE=[Arabic], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
USE [UPIITA_BASE]
GO
CREATE SCHEMA base_upiita AUTHORIZATION Usuarios;
CREATE USER usuarios
FOR LOGIN Fernando

